#!/bin/sh

# Command replacements
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# Application replacements
alias v="nvim"

# Install/remove/search packages
alias i="sudo pacman -S"
alias r="sudo pacman -R"
alias q="sudo pacman -Q"
alias yi="yay -S"
alias yr="yay -R"
alias yq="yay -Q"